FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /src
COPY ["event-consumer-example.csproj", "./"]
RUN dotnet restore "event-consumer-example.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "event-consumer-example.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "event-consumer-example.csproj" -c Release -o /app/publish

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "event-consumer-example.dll" ]

